node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
  listeners.http {
    bind = 18083
  }
}

# HTTP Action to forward MQTT payloads to Python ingestion service
actions.http.timescale_webhook {
  enable = true
  method = "POST"
  url = "http://ingestion:8000/events"
  headers {
    "Content-Type" = "application/json"
  }
  body = """
  {
    "ts": "${ts}",
    "component_id": ${component_id},
    "temperature": ${temperature},
    "humidity": ${humidity}
  }
  """
}

# Rule to transform MQTT messages into HTTP action payloads
rule_engine.rules.my_timescale_rule {
  enable = true
  sql = """
    SELECT
      payload.component_id AS component_id,
      payload.temperature AS temperature,
      payload.humidity AS humidity,
      now() AS ts
    FROM "devices/+/events"
  """
  actions = [
    {
      function = "action:timescale_webhook"
    }
  ]
}