bridges.postgresql.timescale {
  enable = true
  server = "timescaledb:5432"
  database = "appdb"
  username = "admin"
  password = "secret"
  sql = """
    INSERT INTO event_data
    (ts, component_id, temperature, humidity, payload)
    VALUES
    (${ts}, ${component_id}, ${temperature}, ${humidity}, ${payload});
  """
  resource_opts {
    pool_size = 8
  }
}

rule_engine.rules.my_timescale_rule {
  enable = true
  sql = """~
    SELECT
      payload.component_id as component_id,
      payload.temperature as temperature,
      payload.humidity as humidity,
      now() as ts,
      payload as payload
    FROM "devices/+/events"
  ~"""
  actions = [
    {
      function = "bridge:timescale"
    }
  ]
}