version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  emqx:
    image: emqx/emqx-enterprise:latest
    container_name: emqx
    ports:
      - "1883:1883"     # MQTT
      - "18083:18083"   # EMQX dashboard
    environment:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: strongpassword

    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_logs:/opt/emqx/log
      - ./api_keys.conf:/opt/emqx/etc/api_keys.conf:ro
#      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
    depends_on:
      - timescaledb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/status"]
      interval: 5s
      retries: 20
    command: >
      sh -c "
      /opt/emqx/bin/emqx start;
      echo 'Waiting for EMQX...';
      sleep 10;
      echo '=== API KEYS ===';
      /opt/emqx/bin/emqx_ctl api_key list;
      echo '===============';
      tail -f /opt/emqx/log/*;
      "

  setup:
    build: ./setup
    container_name: emqx_setup
    depends_on:
      - emqx
    environment:
      EMQX_HOST: emqx
      EMQX_PORT: 18083
      EMQX_USER: admin
      EMQX_PASS: strongpassword
      INGESTION_URL: http://ingestion:8000/events
    entrypoint: ["python", "/app/create_http_action.py"]

  ingestion:
    build: ./ingestion
    container_name: ingestion2
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: admin
      DB_PASS: secret
    depends_on:
      timescaledb:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  timescale_data:
  emqx_data:
  emqx_logs: