node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
  listeners.http {
    bind = 18083
  }
}

api.key.file = etc/api_keys.conf

# # HTTP action for ingestion service
# actions.http.timescale_webhook {
#   enable = true
#   method = "POST"
#   url = "http://ingestion:8000/events"
# }
# 
# # Rule engine sends MQTT messages to HTTP action
# rule_engine.rules.my_timescale_rule {
#   enable = true
#   sql = """
#     SELECT
#       payload.component_id as component_id,
#       payload.temperature as temperature,
#       payload.humidity as humidity,
#       now() as ts
#     FROM "devices/+/events"
#   """
#   actions = [
#     {
#       function = "action:timescale_webhook"
#     }
#   ]
# }