version: "3.9"

services:
#  emqx:
#    image: emqx/emqx:latest
#    container_name: emqx
#    ports:
#      - "1883:1883"
#      - "18083:18083" #Probably not needed
#    enviroment:
#      EMQX_NAME: emqx

  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
    volumes:
      - questdb_data:/var/lib/questdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - questdb
    volumes:
      - grafana_data:/var/lib/grafana
    
  questdb-init:
    image: questdb/questdb:latest
    depends_on:
      - questdb
    volumes:
      - ./questdb/init.sql:/init.sql
    entrypoint: >
      bash -c "
      until /questdb/bin/psql -h questdb -p 8812 -U admin -d qdb -c '\l'; do
        echo "Waiting..."
        sleep 2
      done
      
      /questdb/bin/psql -h questdb -p 8812 -U admin -d qdb -f /init.sql
      "

volumes:
  questdb_data:
  grafana_data: