{
 "title": "Omron Robot Monitor",
 "description": "Dashboard for monitoring Omron Robot events from the robot_server.",
 "tags": [
  "omron",
  "robot"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "robot",
    "label": "Robot",
    "query": {
     "query": "SELECT DISTINCT robot_address FROM robot_status_events WHERE enriched_data->>'Type' != 'SENSOR_READING' ORDER BY robot_address"
    }
   },
   { "name": "__robot_address_all", "query": "true,false" }
  ]
 },
 "panels": [
  {
   "title": "Live Robot Event Log",
   "type": "logs",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  enriched_data->>'Meaning' AS \"Meaning\",\n  enriched_data->>'Category' AS \"Category\",\n  raw_message AS \"Raw Message\"\nFROM robot_status_events\nWHERE\n  $__timeFilter(ts) AND\n  ($__robot_address_all OR robot_address = '${robot:csv}') AND\n  enriched_data->>'Type' != 'SENSOR_READING'\nORDER BY ts DESC\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Robot Error Counts by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1m', ts) AS \"time\",\n  enriched_data->>'Category' AS metric,\n  COUNT(*)\nFROM robot_status_events\nWHERE\n  $__timeFilter(ts) AND\n  ($__robot_address_all OR robot_address = '${robot:csv}') AND\n  enriched_data->>'Type' = 'ERROR'\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current Robot Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  Category,\n  Meaning,\n  \"time\"\nFROM (\n  SELECT\n    DISTINCT ON (enriched_data->>'Category')\n    ts AS \"time\",\n    enriched_data->>'Category' as \"Category\",\n    enriched_data->>'Meaning' as \"Meaning\"\n  FROM robot_status_events\n  WHERE\n    $__timeFilter(ts) AND\n    ($__robot_address_all OR robot_address = '${robot:csv}') AND\n    enriched_data->>'Type' = 'STATE'\n  ORDER BY\n    enriched_data->>'Category', ts DESC\n) AS latest_states\nORDER BY Category"
    }
   ]
  }
 ]
}